# Telechargement image de base sous linux
# ---------------
FROM oraclelinux:7.0
# Maintainer
# ----------
MAINTAINER Pascal Sené <pascalsene@gmail.com>
# Install wget
# -------------
RUN yum -y installwget
# Download WebLogic 12.1.3
# -------------------------
RUN wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie""http://download.oracle.com/otn-pub/java/jdk/8u25-b17/jdk-8u25-linux-x64.rpm"
# Environment variables required for this build (do NOT change)
# --------------------------------------------------------------
ENV WLS_PKG  fmw_12.1.3.0.0_wls.jar
ENV JAVA_RPM jdk-8u25-linux-x64.rpm
ENV MW_HOME  /u01/oracle/weblogic
# WLS Admin Password (you may change)
# This password is used for:
#  (a) 'oracle' Linux user in this image
# -----------------------------------
ENV ADMIN_PASSWORD welcome1
# Install and configure Oracle JDK 8u25
# -------------------------------------
RUN rpm -i $JAVA_RPM && \
    rm$JAVA_RPM
ENV JAVA_HOME /usr/java/default
ENV CONFIG_JVM_ARGS -Djava.security.egd=file:/dev/./urandom
 
# Configuration utilisateur et packages
# ------------------------------------------------------------
RUN mkdir/u01&& \
    chmoda+xr /u01&& \
    useradd-b /u01-m -s /bin/bashoracle && \
    echooracle:$ADMIN_PASSWORD | chpasswd
# Add files required to build this image
# ------------------------------------------
COPY $WLS_PKG /u01/
COPY setup/* /u01/
# Change the open file limits in /etc/security/limits.conf
# ---------------------------------------------------------
RUN sed-i '/.*EOF/d'/etc/security/limits.conf && \
    echo"* soft nofile 16384">> /etc/security/limits.conf && \
    echo"* hard nofile 16384">> /etc/security/limits.conf && \
    echo"# EOF">> /etc/security/limits.conf
# Modification du kernet
-----------------------------------------------------
RUN echo"net.core.rmem_max=4192608"> /u01/oracle/.sysctl.conf && \
    echo"net.core.wmem_max=4192608">> /u01/oracle/.sysctl.conf && \
    sysctl -e -p /u01/oracle/.sysctl.conf
# Ajustement des permissions du FS /u01 comme user 'oracle' pour effectuer la WLS installation
RUN chownoracle:oracle -R /u01
WORKDIR /u01
USER oracle
# Installation of WebLogic
# -------------------------
RUN mkdir/u01/oracle/.inventory
RUN java -jar $WLS_PKG -silent -responseFile /u01/install.file-invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME
RUN rm$WLS_PKG /u01/oraInst.loc /u01/install.file
WORKDIR /u01/oracle/weblogic
USER oracle
# Lancement de bash comme etape finale
# --------------------------------------
CMD ["/bin/bash"]
